### ISSUE TITLE
Error when converting repository

### ISSUE THREAD

**Issue by philipstarkey** [chrisjbillington/hg-export-tool#3]
I'm trying to convert https://bitbucket.org/dsbarker/labscript_utils

I get the following error from fast-export.sh (note it was a real pain to get this error out! I had to manually preserve the temp directory and then manually run the conversion command as `subprocess.check_call` and even `subprocess.check_output` don't return the traceback)

Traceback (most recent call last):

```
  File "C:/Users/user/Documents/Programming/hg-export-tool/fast-export/hg-fast-export.py", line 718, in <module>
    plugins=plugins_dict))
  File "C:/Users/user/Documents/Programming/hg-export-tool/fast-export/hg-fast-export.py", line 534, in hg2git
    if not verify_heads(ui,repo,heads_cache,force,branchesmap):
  File "C:/Users/user/Documents/Programming/hg-export-tool/fast-export/hg-fast-export.py", line 495, in verify_heads
    % (b.decode('utf8'), sha1.decode('utf8'), c.decode('utf8'))
AttributeError: 'NoneType' object has no attribute 'decode'
```

**Comment by philipstarkey** [comment]
So the immediate traceback is caused by the Python 3 port not expecting None types on the relevant line. I'm running it under Python 2.7 but I don't think that matters.

Fixing that isn't sufficient though because it doesn't explain why that line of code is being hit. Hitting it will cause the subprocess to exit with a non zero error code anyway (at least according to a hg-fast-export issue I found). It may be relevant that I'm running on Windows and may have something to do with specific branches in the repository I'm trying to convert. That's about as far as I got with my debugging.

**Comment by chrisjbillington** [comment]
The code that's raising an error is about verifying that an *already existing* git repository is consistent with a mercurial repository about to be used for an incremental update. hg-export-tool shouldn't be doing that, it should be looking at an empty git repository. This makes me think you only saw this error because of the hack you had to do to see the error, and that when you ran the conversion command, the git repo already existed and was not empty (even if you deleted its contents and reset branches to make it look like an empty repo, hg-fast-export stores a file in the .git directory that caches the state from what it did last time, which is what it is checking against).

What I see though if I run hg-export-tool from scratch, is also that it exists with exit code 1, and I think this is coming fram `git fast-import` as called in `hg-fast-export.sh`, and not actually from `hg-fast-export.py`. That may be why you didn't see any Python traceback - there wouldn't have been one.

`git fast-import` is printing this warning, which I would guess is why it exits with status 1:

```
warning: Not updating refs/heads/Bugfix (new tip 9256c6abca25b1361af1379f49055eb287f55c42 does not contain 9938deb2c738c0c7acb71255d96bbf7c49a320b1)
```

I see this issue on Windows only, but for all combinations of Py2/Py3/mercurial 5.3/mercurial 4.8 that I tried.

I am pretty sure that this must be something about case-insensitivity of filenames on Windows, since there is a `bugfix` branch already, and the warning is about a `Bugfix` branch.

Git has been told to be case sensitive, but it sounds like there are inevitable issues regardless, if you use branch names that are the same but differ only by case, because at some point they are stored on disk as files with the branch name as the filename.

I'll see if the issue goes away if I use a branch mapping file to rename the branches that are named the same modulo case. Renaming `Bugfix` -> `bugfix` should be fine since it's presumably not a topological head (i.e. it's been merged in), and hg-fast-export only has issues with multiple topological heads in the same branch.

**Comment by chrisjbillington** [comment]
Oh and the failure to print the error message, yeah that's a bug. A subsequent fix to hg-fast-export would have fixed it on Python2, but it's still an issue on Python 3, so I'll fix it there too...

**Comment by chrisjbillington** [comment]
Have fixed the failure to print an error message, and as for the actual issue, the answer is that we need to use a branch mapping file to rename `Bugfix → bugfix`. Will elaborate by email.
